require "test_helper"

class ArticleTest < ActiveSupport::TestCase
  fixtures :authors, :categories, :tags # articles fixture is loaded by default

  setup do
    @author = authors(:one)
    @category = categories(:one)
    @tag = tags(:one)

    # Base article from fixtures, ensure it's in a known valid state for most tests
    @article = articles(:one)
    @article.author = @author
    @article.category = @category
    @article.title = "Valid Article Title from Setup" # Ensure unique title for slug tests
    @article.content = "This is some valid content for testing purposes."
    @article.status = :draft # Default status
    @article.published_at = nil # Consistent with draft status
    @article.reading_time = 1 # Default valid reading time, will be recalculated on save if content changes
    @article.meta_description = "A meta description."
    @article.excerpt = "An excerpt."
    # featured_image is not validated for presence in the model by default
    @article.save! # Save to ensure slug is generated, etc.
  end

  # Validations
  test "should be valid with valid attributes" do
    assert @article.valid?, "Article with valid attributes should be valid. Errors: #{@article.errors.full_messages.join(", ")}"
  end

  test "should validate presence of title" do
    @article.title = nil
    assert_not @article.valid?, "Article should be invalid without a title"
    assert_includes @article.errors[:title], "can't be blank"
  end

  test "should validate minimum length of title (5 chars)" do
    @article.title = "four"
    assert_not @article.valid?, "Article title should be too short"
    assert_includes @article.errors[:title], "is too short (minimum is 5 characters)"
  end

  test "should validate maximum length of title (200 chars)" do
    @article.title = "a" * 201
    assert_not @article.valid?, "Article title should be too long"
    assert_includes @article.errors[:title], "is too long (maximum is 200 characters)"
  end

  test "should validate presence of slug" do
    # Slug is normally generated by callback. To test presence validation, we bypass it.
    @article.slug = nil
    assert_not @article.valid?, "Article should be invalid without a slug"
    assert_includes @article.errors[:slug], "can't be blank"
  end

  test "should validate uniqueness of slug" do
    # Ensure the slug for @article is what we expect after setup's save!
    expected_slug = "valid-article-title-from-setup" # Based on @article.title in setup
    assert_equal expected_slug, @article.slug, "Slug was not generated as expected in setup"

    duplicate_article = Article.new(
      title: "Another Article", # Different title to avoid slug regeneration based on this title
      author: @author,
      category: @category,
      content: "Some content."
    )
    duplicate_article.slug = @article.slug # Force the same slug
    assert_not duplicate_article.valid?, "Article with a duplicate slug should be invalid"
    assert_includes duplicate_article.errors[:slug], "has already been taken"
  end

  test "should validate maximum length of meta_description (160 chars)" do
    @article.meta_description = "a" * 161
    assert_not @article.valid?, "Meta description should be too long"
    assert_includes @article.errors[:meta_description], "is too long (maximum is 160 characters)"
  end

  test "should validate maximum length of excerpt (150 chars)" do
    @article.excerpt = "a" * 151
    assert_not @article.valid?, "Excerpt should be too long"
    assert_includes @article.errors[:excerpt], "is too long (maximum is 150 characters)"
  end

  test "should validate presence of content" do
    @article.content = nil
    assert_not @article.valid?, "Article should be invalid without content"
    assert_includes @article.errors[:content], "can't be blank"
  end

  test "should validate numericality of reading_time (integer, greater than 0)" do
    @article.reading_time = 0
    assert_not @article.valid?, "Reading time should be invalid if 0"
    assert_includes @article.errors[:reading_time], "must be greater than 0"

    @article.reading_time = -1
    assert_not @article.valid?, "Reading time should be invalid if negative"
    assert_includes @article.errors[:reading_time], "must be greater than 0"
    
    @article.reading_time = 1.5
    # This validation is for direct assignment. The model's callback `calculate_reading_time` uses `ceil`,
    # ensuring an integer. The `only_integer` validation applies to the value before type casting if it's a string,
    # or if a float is directly assigned.
    assert_not @article.valid?, "Reading time should be invalid if a float"
    assert_includes @article.errors[:reading_time], "must be an integer"


    @article.reading_time = "abc"
    assert_not @article.valid?, "Reading time should be invalid if not a number"
    assert_includes @article.errors[:reading_time], "is not a number"
  end

  test "should validate presence of status" do
    @article.status = nil
    assert_not @article.valid?, "Article should be invalid without a status"
    assert_includes @article.errors[:status], "can't be blank"
  end

  test "should validate presence of published_at if status is published" do
    @article.status = :published
    @article.published_at = nil
    assert_not @article.valid?, "Published article should be invalid without published_at"
    assert_includes @article.errors[:published_at], "can't be blank"

    @article.status = :draft
    @article.published_at = nil # Reset for this part of the test
    assert @article.valid?, "Draft article should be valid with nil published_at. Errors: #{@article.errors.full_messages.join(", ")}"
  end

  # Associations
  test "should belong to an author" do
    assert_respond_to @article, :author
    assert_instance_of Author, @article.author, "Article's author should be an Author instance"
  end

  test "should belong to a category" do
    assert_respond_to @article, :category
    assert_instance_of Category, @article.category, "Article's category should be a Category instance"
  end

  test "should have and belong to many tags" do
    assert_respond_to @article, :tags
    assert_respond_to @article, :tag_ids # Check for the association helper method
    
    initial_tag_count = @article.tags.count
    @article.tags << @tag
    assert_equal initial_tag_count + 1, @article.tags.count, "Tag count should increment"
    assert_includes @article.tags, @tag, "Article should include the added tag"
  end

  test "should have rich text content" do
    assert @article.respond_to?(:content), "Article should respond to :content"
    assert @article.content.respond_to?(:body), "Article's content should respond to :body (ActionText)"
    
    @article.content = "New rich content"
    @article.save!
    @article.reload
    assert_equal "New rich content", @article.content.body.to_plain_text, "Plain text of rich content body should match"
  end

  test "should have one attached featured_image (if validation active)" do
    assert @article.respond_to?(:featured_image), "Article should respond to :featured_image"
    assert @article.featured_image.respond_to?(:attach), "Featured image should be attachable"
    # Note: The model's `validates :featured_image` is commented out.
    # If it were active, this test would need to ensure an image is attached for validity,
    # and test invalidity if not attached.
    # e.g., @article.featured_image.attach(io: File.open(Rails.root.join('test', 'fixtures', 'files', 'test_image.png')), filename: 'test_image.png', content_type: 'image/png')
    # assert @article.valid?
  end

  # Callbacks
  test "should generate slug from title before validation if title is present and changed" do
    article = Article.new(title: "A New Unique Test Article", author: @author, category: @category, content: "Some content.")
    assert article.valid? # Trigger before_validation callbacks
    assert_equal "a-new-unique-test-article", article.slug, "Slug was not generated correctly"
  end
  
  test "should not generate new slug if title is present but unchanged" do
    article = Article.create!(title: "Original Title For Slug Test", author: @author, category: @category, content: "Content")
    original_slug = article.slug
    article.meta_description = "Changing something else"
    article.save! # This will trigger callbacks
    assert_equal original_slug, article.slug, "Slug should not change if title hasn't changed"
  end

  test "should generate an empty slug if title is an empty string (and rely on presence validation for slug)" do
    article = Article.new(title: "", author: @author, category: @category, content: "Some content.")
    article.valid? # Trigger slug generation
    assert_equal "", article.slug, "Slug should be an empty string if title is empty string"
    assert_includes article.errors[:slug], "can't be blank", "Presence validation for slug should fail for empty string slug"
  end
  
  test "should not attempt to generate slug if title is nil (and rely on presence validation for title)" do
    article = Article.new(title: nil, author: @author, category: @category, content: "Some content.")
    original_slug_before_validation = article.slug # which is nil
    article.valid? # Trigger slug generation attempt and validations
    assert_nil article.slug, "Slug should remain nil if title is nil"
    assert_includes article.errors[:title], "can't be blank"
    # If slug was nil and title is nil, slug generation is skipped.
    # If slug had a previous value, it would retain it.
    # The `validates :slug, presence: true` would catch a nil slug anyway.
  end


  test "should calculate reading time before save" do
    # Using a specific word count to predict reading time
    words_per_minute = 200
    word_count = 450 # Approx 2.25, so ceil should be 3
    content_text = "word " * word_count
    
    article = Article.new(title: "Test Reading Time Calculation", author: @author, category: @category, content: content_text)
    article.save! # Trigger before_save callback
    
    expected_reading_time = (word_count / words_per_minute.to_f).ceil
    assert_equal expected_reading_time, article.reading_time, "Reading time was not calculated correctly"
  end

  test "should set default status to draft on new record initialization" do
    article = Article.new
    assert_equal "draft", article.status, "Default status should be draft for a new article"
  end

  # Scopes
  test "published scope should return only published articles with published_at set" do
    published_and_dated = Article.create!(title: "Published Dated", author: @author, category: @category, content: "content", status: :published, published_at: Time.current)
    published_not_dated = Article.create!(title: "Published Not Dated", author: @author, category: @category, content: "content", status: :published, published_at: nil) # This is invalid by model rules
    draft_article = Article.create!(title: "Draft Scoped", author: @author, category: @category, content: "content", status: :draft)

    published_articles_scope = Article.published
    
    assert_includes published_articles_scope, published_and_dated, "Scope should include published and dated article"
    # The model validation `validates :published_at, presence: true, if: -> { status == :published }`
    # means published_not_dated shouldn't exist in a valid state.
    # If it somehow does, the scope `where.not(published_at: nil)` would correctly exclude it.
    assert_not_includes published_articles_scope, published_not_dated, "Scope should exclude published article with nil published_at"
    assert_not_includes published_articles_scope, draft_article, "Scope should exclude draft article"
  end

  test "featured scope should return only featured articles" do
    featured_article = Article.create!(title: "Featured Scoped", featured: true, author: @author, category: @category, content: "content", status: :published, published_at: Time.current)
    non_featured_article = Article.create!(title: "Non-Featured Scoped", featured: false, author: @author, category: @category, content: "content", status: :published, published_at: Time.current)

    featured_articles_scope = Article.featured
    assert_includes featured_articles_scope, featured_article, "Scope should include featured article"
    assert_not_includes featured_articles_scope, non_featured_article, "Scope should exclude non-featured article"
  end
  
  test "not_deleted scope should exclude articles with deleted_at set" do
    not_deleted_article = Article.create!(title: "Not Deleted Scoped", author: @author, category: @category, content: "content", status: :published, published_at: Time.current, deleted_at: nil)
    deleted_article = Article.create!(title: "Deleted Scoped", author: @author, category: @category, content: "content", status: :published, published_at: Time.current, deleted_at: Time.current)

    not_deleted_articles_scope = Article.not_deleted
    assert_includes not_deleted_articles_scope, not_deleted_article, "Scope should include not deleted article"
    assert_not_includes not_deleted_articles_scope, deleted_article, "Scope should exclude deleted article"
  end

  # Enums
  test "should have correct enum values for status" do
    # Note: Rails 7.1+ default enum storage is integer. `Article.statuses.keys` gives string keys.
    expected_statuses = %w[draft review published archived]
    assert_equal expected_statuses, Article.statuses.keys, "Enum keys for status are incorrect"
  end

  test "should allow setting and querying status enum values" do
    @article.draft!
    assert @article.draft?, "Article should be in draft status"

    @article.review!
    assert @article.review?, "Article should be in review status"

    @article.published!
    @article.published_at = Time.current # ensure published_at is set for validation for published status
    assert @article.save, "Saving published article should be successful"
    assert @article.published?, "Article should be in published status"

    @article.archived!
    assert @article.archived?, "Article should be in archived status"
  end
end
