require "test_helper"

class AuthorsControllerTest < ActionDispatch::IntegrationTest
  fixtures :authors

  DUMMY_AVATAR_BASENAME = "dummy_author_controller_avatar.png".freeze
  DUMMY_AVATAR_PATH = Rails.root.join("tmp", DUMMY_AVATAR_BASENAME).freeze

  def self.ensure_dummy_avatar_exists
    return if File.exist?(DUMMY_AVATAR_PATH)
    FileUtils.mkdir_p(Rails.root.join("tmp"))
    File.open(DUMMY_AVATAR_PATH, "w") { |f| f.write("dummy avatar content for author controller test") }
  end
  ensure_dummy_avatar_exists

  setup do
    @author = authors(:author_jane) # Using descriptive fixture name
    # Ensure fixture data is unique if necessary for specific test logic,
    # though descriptive fixtures should ideally be pre-configured with valid, distinct data.
    # Example: if a test relies on @author.email being something specific and unique for that test run.
    # @author.update!(email: "author_jane_ctrl_test_#{Time.now.to_f}@example.com")

    @other_author = authors(:author_john) # Using another descriptive fixture for tests needing a second author
  end

  test "should get index and assign authors" do
    get authors_url
    assert_response :success
    assert_not_nil assigns(:authors), "@authors instance variable should be assigned"
  end

  test "should get new and assign a new author" do
    get new_author_url
    assert_response :success
    assert_instance_of Author, assigns(:author), "A new Author instance should be assigned"
    assert assigns(:author).new_record?, "Assigned @author should be a new record"
  end

  test "should create author with valid parameters" do
    author_params = {
      first_name: "NewFirstCtrl",
      last_name: "NewLastCtrl",
      email: "new.author.create.ctrl.#{Time.now.to_i}@example.com", # Ensure unique email
      status: :active,
      role: :writer
    }

    assert_difference("Author.count", 1, "Author count should increment by 1") do
      post authors_url, params: { author: author_params }
    end

    created_author = Author.last
    assert_redirected_to author_url(created_author), "Should redirect to the created author's show page"
    assert_equal "Author was successfully created.", flash[:notice], "Flash notice for creation should be set"
    assert_equal author_params[:first_name], created_author.first_name
    assert_equal author_params[:email], created_author.email
    # Slug should be auto-generated by model callback
    assert_equal "#{author_params[:first_name].parameterize}-#{author_params[:last_name].parameterize}", created_author.slug
  end

  test "should create author with an avatar" do
    avatar_file = fixture_file_upload(DUMMY_AVATAR_PATH, "image/png")
    author_params_with_avatar = {
      first_name: "AvatarFirstCtrl",
      last_name: "UserLastCtrl",
      email: "avatar.user.create.ctrl.#{Time.now.to_i}@example.com",
      avatar: avatar_file
    }

    assert_difference("Author.count", 1) do
      post authors_url, params: { author: author_params_with_avatar }
    end

    created_author = Author.last
    assert created_author.avatar.attached?, "Avatar should be attached to the created author"
    assert_redirected_to author_url(created_author)
  end

  test "should show author and assign it" do
    get author_url(@author) # @author is authors(:author_jane)
    assert_response :success
    assert_equal @author, assigns(:author), "@author instance variable should be assigned correctly"
  end

  test "should get edit for an author and assign it" do
    get edit_author_url(@author)
    assert_response :success
    assert_equal @author, assigns(:author), "@author instance variable should be assigned for edit"
  end

  test "should update author with valid parameters" do
    updated_first_name = "UpdatedFirstNameCtrlTest#{Time.now.to_i}"
    updated_email = "updated.author.ctrl.update.#{Time.now.to_i}@example.com"

    patch author_url(@author), params: {
      author: {
        first_name: updated_first_name,
        email: updated_email
      }
    }
    assert_redirected_to author_url(@author), "Should redirect to the author's show page after update"
    @author.reload

    assert_equal updated_first_name, @author.first_name, "Author first_name should be updated"
    assert_equal updated_email, @author.email, "Author email should be updated"
    assert_equal "Author was successfully updated.", flash[:notice], "Flash notice for update should be set"
  end

  test "should destroy author" do
    # Create an author that can be safely deleted without affecting other tests using @author or @other_author
    author_to_delete = Author.create!(first_name: "ToDeleteCtrlFirst", last_name: "ToDeleteCtrlLast", email: "to.delete.ctrl.#{Time.now.to_i}@example.com")

    assert_difference("Author.count", -1, "Author count should decrease by 1") do
      delete author_url(author_to_delete)
    end

    assert_redirected_to authors_url, "Should redirect to authors index page after destruction"
    assert_equal "Author was successfully destroyed.", flash[:notice], "Flash notice for destruction should be set"
  end

  test "should not create author with invalid parameters (e.g., blank first_name)" do
    assert_no_difference("Author.count", "Author count should not change with invalid params") do
      post authors_url, params: { author: { first_name: "", last_name: "LastNameCtrl", email: "invalid.creation.ctrl@example.com" } }
    end
    assert_response :unprocessable_entity, "Response should be :unprocessable_entity for invalid create params"
    assert_template :new, "Should re-render the 'new' template"
  end

  test "should not update author with invalid parameters (e.g., blank email)" do
    original_email = @author.email
    patch author_url(@author), params: { author: { email: "" } } # Invalid: email is blank
    assert_response :unprocessable_entity, "Response should be :unprocessable_entity for invalid update params"
    assert_template :edit, "Should re-render the 'edit' template"
    @author.reload
    assert_equal original_email, @author.email, "Author email should not change with invalid update params"
  end

  # Note: The controller's set_author uses Author.find (by ID).
  # If FriendlyId (finding by slug) is desired for this controller,
  # set_author should be changed to Author.friendly.find, and a test for slug finding should be added.
  # Example:
  # test "should show author using slug" do
  #   get author_url(id: @author.slug) # This assumes to_param returns slug
  #   assert_response :success
  #   assert_equal @author, assigns(:author)
  # end


  def self.cleanup_dummy_avatar
    FileUtils.rm_f(DUMMY_AVATAR_PATH) if File.exist?(DUMMY_AVATAR_PATH)
  end
  Minitest.after_run { cleanup_dummy_avatar }
end
