require "test_helper"

class CategoriesControllerTest < ActionDispatch::IntegrationTest
  fixtures :categories, :articles, :authors # Ensure authors are available for creating articles

  setup do
    @category = categories(:one)
    @category.update!(
      name: "Category Controller Test One", 
      description: "Test description for category one in controller test", 
      slug: "category-controller-test-one"
    )

    @other_category = categories(:two) 
    @other_category.update!(
      name: "Category Controller Test Two", 
      description: "Test description for category two in controller test", 
      slug: "category-controller-test-two"
    )

    # Ensure @category has at least one article for the show action test
    author_for_article = authors(:one) # Assuming authors(:one) is a valid author
    author_for_article.update!(email: "category_ctrl_author@example.com") unless author_for_article.valid?

    # Ensure the article fixture is associated with @category or create a new one.
    # If articles(:one) is used, make sure its category_id points to @category.id or re-associate.
    article_for_show = articles(:one) 
    article_for_show.update!(category: @category, author: author_for_article, title: "Article for Category Show Test", content: "Content", status: :published, published_at: Time.current)
  end

  test "should get index and assign categories" do
    get categories_url
    assert_response :success
    assert_not_nil assigns(:categories), "@categories instance variable should be assigned"
  end

  test "should get new and assign a new category" do
    get new_category_url
    assert_response :success
    assert_instance_of Category, assigns(:category), "A new Category instance should be assigned"
    assert assigns(:category).new_record?, "Assigned @category should be a new record"
  end

  test "should create category with valid parameters" do
    unique_name = "New Test Category Create #{Time.now.to_i}"
    category_params = {
      name: unique_name,
      description: "Description for the new test category created.",
      status: :active 
    }

    assert_difference("Category.count", 1, "Category count should increment by 1") do
      post categories_url, params: { category: category_params }
    end

    created_category = Category.last
    assert_redirected_to category_url(created_category), "Should redirect to the created category's show page"
    assert_equal "Category was successfully created.", flash[:notice], "Flash notice for creation should be set"
    assert_equal unique_name, created_category.name
    # Slug should be auto-generated by model callback based on name
    assert_equal unique_name.parameterize, created_category.slug
  end

  test "should show category, assign instance variables, and render articles/index template" do
    get category_url(@category) # Uses @category.to_param which should be its slug due to FriendlyId
    assert_response :success
    
    assert_equal @category, assigns(:category), "@category instance variable should be assigned correctly"
    assert_not_nil assigns(:articles), "@articles instance variable (for articles in this category) should be assigned"
    assert_not_nil assigns(:categories), "@categories instance variable (for all categories, e.g. for sidebar) should be assigned"
    
    assigns(:articles).each do |article|
      assert_equal @category.id, article.category_id, "Articles shown should belong to the current category"
    end
    
    assert_template "articles/index", "Should render the 'articles/index' template for category show page"
  end
  
  test "should show category using its slug directly in URL parameter" do
    get category_url(id: @category.slug) # Explicitly use slug in 'id' param
    assert_response :success
    assert_equal @category, assigns(:category), "Should find category by slug and assign it"
  end

  test "should get edit for a category and assign it" do
    get edit_category_url(@category)
    assert_response :success
    assert_equal @category, assigns(:category), "@category instance variable should be assigned for edit"
  end

  test "should update category with valid parameters" do
    updated_name = "Updated Category Name Test #{Time.now.to_i}"
    patch category_url(@category), params: { 
      category: { 
        name: updated_name, 
        description: "Updated category description test."
      } 
    }
    assert_redirected_to category_url(@category), "Should redirect to the category's show page after update"
    @category.reload
    
    assert_equal updated_name, @category.name, "Category name should be updated"
    assert_equal "Updated category description test.", @category.description, "Category description should be updated"
    assert_equal "Category was successfully updated.", flash[:notice], "Flash notice for update should be set"
  end

  test "should destroy category" do
    # Category model has `has_many :articles, dependent: :nullify`.
    # Destroying a category should nullify category_id in its articles.
    category_to_delete = Category.create!(name: "Delete Me Category Test", description: "This category is for deletion test.")
    # Optionally, create an article for it to check nullification if needed, but model test already covers this.

    assert_difference("Category.count", -1, "Category count should decrease by 1") do
      delete category_url(category_to_delete)
    end

    assert_redirected_to categories_url, "Should redirect to categories index page after destruction"
    assert_equal "Category was successfully destroyed.", flash[:notice], "Flash notice for destruction should be set"
  end

  test "should not create category with invalid parameters (e.g., blank name)" do
    assert_no_difference("Category.count", "Category count should not change with invalid params") do
      post categories_url, params: { category: { name: "", description: "Attempt to create with blank name" } }
    end
    assert_response :unprocessable_entity, "Response should be :unprocessable_entity for invalid create params"
    assert_template :new, "Should re-render the 'new' template"
  end

  test "should not update category with invalid parameters (e.g., blank name)" do
    original_name = @category.name
    patch category_url(@category), params: { category: { name: "" } } # Invalid: name is blank
    assert_response :unprocessable_entity, "Response should be :unprocessable_entity for invalid update params"
    assert_template :edit, "Should re-render the 'edit' template"
    @category.reload
    assert_equal original_name, @category.name, "Category name should not change with invalid update params"
  end
end
